/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(auth)'}/SignIn` | `/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Register` | `/Register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/UserInfo` | `/UserInfo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Search` | `/Search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Stats` | `/Stats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Workout` | `/Workout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile/edit` | `/Profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile/followers` | `/Profile/followers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile/following` | `/Profile/following`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile/requests` | `/Profile/requests`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `${'/(auth)'}/SignIn` | `/SignIn`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/Register` | `/Register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/UserInfo` | `/UserInfo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Search` | `/Search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Stats` | `/Stats`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Workout` | `/Workout`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Profile/edit` | `/Profile/edit`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Profile/followers` | `/Profile/followers`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Profile/following` | `/Profile/following`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Profile/requests` | `/Profile/requests`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `${'/(auth)'}/SignIn${`?${string}` | `#${string}` | ''}` | `/SignIn${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/Register${`?${string}` | `#${string}` | ''}` | `/Register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/UserInfo${`?${string}` | `#${string}` | ''}` | `/UserInfo${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Home${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Search${`?${string}` | `#${string}` | ''}` | `/Search${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Stats${`?${string}` | `#${string}` | ''}` | `/Stats${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Workout${`?${string}` | `#${string}` | ''}` | `/Workout${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Profile/edit${`?${string}` | `#${string}` | ''}` | `/Profile/edit${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Profile/followers${`?${string}` | `#${string}` | ''}` | `/Profile/followers${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Profile/following${`?${string}` | `#${string}` | ''}` | `/Profile/following${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Profile${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Profile/requests${`?${string}` | `#${string}` | ''}` | `/Profile/requests${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(auth)'}/SignIn` | `/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Register` | `/Register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/UserInfo` | `/UserInfo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Search` | `/Search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Stats` | `/Stats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Workout` | `/Workout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile/edit` | `/Profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile/followers` | `/Profile/followers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile/following` | `/Profile/following`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile/requests` | `/Profile/requests`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
